### ISSUE TITLE
Some more fixes and request for a tag

### ISSUE THREAD

**Issue by huth** [joshbressers/ularn#10]
Hi! When you've got some spare minutes, could you please consider to merge https://github.com/joshbressers/ularn/pull/9 ?
And once the fixes are merged (or not if you don't like them), could you please tag the current master, and push the tag to github, so that there is a version one can refer to, and so that there are also tarballs available for download? ... that would be great!

 Thanks,
  Thomas

**Comment by joshbressers** [comment]
Apologies for the delay. These changes look good. Thanks for the PR
