### ISSUE TITLE
There is no Configure file

### ISSUE THREAD

**Issue by jiocy** [joshbressers/ularn#2]
The instructions state:
"1. In your source directory (that should be where this file and the README are) type "`./Configure`" and hit return."
However there is no file by that name, the closest things are `config.guess` and `config.sub`. Those files don't do what Configure is described as doing.

I tried simply running make and skipping the configure step, but there were some issues with permissions, and with missing files in /usr/share/larn that didn't get created.

If you know what I'm doing wrong, that would be appreciated!

**Comment by joshbressers** [comment]
Run ./autogen.sh first. That should create everything you need.

**Comment by jiocy** [comment]
Thank you so much, that worked! It never ended up asking me any questions, but it made a working executable in src called Ularn. Is it correct (in larn/ularn) for empty squares to be blank instead of filled with the traditional `.` character? If so, I think I'm good to head out and die in fun new ways, thanks again!

`$ make
...
make[1]: Leaving directory '/home/ocol/ularn/src'
make[1]: Entering directory '/home/ocol/ularn/data'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/ocol/ularn/data'

$ make install
for subdir in src data; do \
	(cd $subdir && make  all) || exit 1; \
done
make[1]: Entering directory '/home/ocol/ularn/src'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/ocol/ularn/src'
make[1]: Entering directory '/home/ocol/ularn/data'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/ocol/ularn/data'
if test ! -d /usr/local/share/doc//Ularn-1.7.0 ; then mkdir -p /usr/local/share/doc//Ularn-1.7.0 ; fi
mkdir: cannot create directory ‘/usr/local/share/doc’: Permission denied
make: *** [Makefile:64: install] Error 1`
