### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by hgaukel** [joshbressers/ularn#3]
When I run autoconf and then make, I get this error:
io.o: In function `init_term':
/home/h/Documents/ularn/src/io.c:508: undefined reference to `tgetent'
/home/h/Documents/ularn/src/io.c:517: undefined reference to `tgetstr'
/home/h/Documents/ularn/src/io.c:518: undefined reference to `tgetstr'
/home/h/Documents/ularn/src/io.c:519: undefined reference to `tgetstr'
/home/h/Documents/ularn/src/io.c:520: undefined reference to `tgetstr'
/home/h/Documents/ularn/src/io.c:521: undefined reference to `tgetstr'
io.o:/home/h/Documents/ularn/src/io.c:522: more undefined references to `tgetstr' follow
io.o: In function `init_term':
/home/h/Documents/ularn/src/io.c:537: undefined reference to `tgetflag'
io.o: In function `lflush':
/home/h/Documents/ularn/src/io.c:690: undefined reference to `tgoto'
/home/h/Documents/ularn/src/io.c:690: undefined reference to `tputs'
/home/h/Documents/ularn/src/io.c:676: undefined reference to `tputs'
/home/h/Documents/ularn/src/io.c:672: undefined reference to `tputs'
/home/h/Documents/ularn/src/io.c:667: undefined reference to `tputs'
/home/h/Documents/ularn/src/io.c:684: undefined reference to `tputs'
io.o:/home/h/Documents/ularn/src/io.c:680: more undefined references to `tputs' follow
io.o: In function `lflush':
/home/h/Documents/ularn/src/io.c:711: undefined reference to `tgoto'
/home/h/Documents/ularn/src/io.c:711: undefined reference to `tputs'
/home/h/Documents/ularn/src/io.c:713: undefined reference to `tputs'
/home/h/Documents/ularn/src/io.c:714: undefined reference to `tgoto'
/home/h/Documents/ularn/src/io.c:714: undefined reference to `tputs'
/home/h/Documents/ularn/src/io.c:700: undefined reference to `tgoto'
/home/h/Documents/ularn/src/io.c:700: undefined reference to `tputs'
/home/h/Documents/ularn/src/io.c:702: undefined reference to `tputs'
/home/h/Documents/ularn/src/io.c:706: undefined reference to `tgoto'
/home/h/Documents/ularn/src/io.c:706: undefined reference to `tputs'
/home/h/Documents/ularn/src/io.c:708: undefined reference to `tputs'
savelev.o: In function `fill_buffer':
/home/h/Documents/ularn/src/savelev.c:466: undefined reference to `uncompress'
savelev.o: In function `flush_buffer':
/home/h/Documents/ularn/src/savelev.c:495: undefined reference to `compress'
tty.o: In function `gettty':
/home/h/Documents/ularn/src/tty.c:80: undefined reference to `ospeed'
collect2: error: ld returned 1 exit status
Makefile:66: recipe for target 'Ularn' failed
make[1]: *** [Ularn] Error 1
make[1]: Leaving directory '/home/h/Documents/ularn/src'
Makefile:57: recipe for target 'all' failed
make: *** [all] Error 1

How can I fix this?

**Comment by joshbressers** [comment]
This should be fixed now, please open a new issue if you still can't build
