### ISSUE TITLE
Still doesn'

### ISSUE THREAD

**Issue by suetanvil** [joshbressers/ularn#7]
I just pulled it and did a `./autogen.sh; ./configure; make` and get a link error.  This is because `-lncurses -lz` appears before the object files in the link command line; for some reason, my `ld` can't handle that.

The way to fix this in the autoconf script is to put libs in SYS_LIBRARIES instead of LDFLAGS in src/Makefile.in.

**Comment by suetanvil** [comment]
BTW, manually fixing this will produce a working executable.

**Comment by joshbressers** [comment]
It seems I changed my makefile, not the makefile.in

A PR would be welcome, otherwise I'll try to get to this sometime this week.

**Comment by suetanvil** [comment]
I'll do it if I have the time this week.
