### ISSUE TITLE
Problems when cross-compiling ularn

### ISSUE THREAD

**Issue by huth** [joshbressers/ularn#8]
Hi! I've had some trouble to cross-compile ularn. Please consider to include these fixes here:
https://github.com/huth/ularn/commits/fixes

**Comment by joshbressers** [comment]
Those seem pretty sane, can you submit a PR?

Thanks.

-- 
    JB

**Comment by huth** [comment]
PR should already be there:
https://github.com/joshbressers/ularn/pull/6

**Comment by joshbressers** [comment]
I merged this PR, thanks!
